"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const controllers_1 = require("./controllers");
const router = express_1.Router();
router.use("/", controllers_1.IndexController.index);
router.use("**", controllers_1.IndexController.notFound);
router.post("/login", controllers_1.AuthController.login);
router.post("/recover-password", controllers_1.AuthController.recoverPassword);
exports.default = router;
